version: "3.7"

services:

  rstudio:
    image: rocker/tidyverse:4.0.0
    container_name: rvest
    volumes:
      - ./:/home/user
    environment:
      USER: user
      PASSWORD: user
    ports:
      - 8787:8787

  selenium:
    image: selenium/standalone-firefox:4.0.0
    shm_size: 4gb
    container_name: selenium
    ports:
      - 4444:4444